### ISSUE TITLE
scopeNameが異なる

### ISSUE THREAD

**Issue by offxi** [msysyamamoto/vscode-fluentd#1]
インストールし使ってみようとしたところ以下のエラーが発生しました。

`The mode has failed while tokenizing the input.`

当方Visual Studio Codeの拡張は素人なので恐縮ですが、以下の部分でfluentdとdigで異なっていて良いのでしょうか?

- package.json の contributes.grammars.scopeName が source.fluentd
- syntaxes/fluentd.tmLanguage.json の言語部分が fluentd
- syntaxes/fluentd.tmLanguage.json のscopeName が source.dig

触ってみた感じ、source.digをsource.fluentdにしてみたところエラーは出ませんでした。

環境は Mac Sieera 10.12.6, Visual Studio Code 1.17.2 です。

**Comment by msysyamamoto** [comment]
Thanks for the report.

[別のextension](https://github.com/msysyamamoto/vscode-digdag)のコードをコピーした際の直し漏れでした。
